# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='csv.proto',
  package='sentient',
  syntax='proto3',
  serialized_options=_b('\n\010sentientB\tCSVProtos'),
  serialized_pb=_b('\n\tcsv.proto\x12\x08sentient\"6\n\x0fParseCsvRequest\x12\x0f\n\x07\x63svPath\x18\x01 \x01(\t\x12\x12\n\noutputPort\x18\x02 \x01(\x05\"&\n\x10ParseCsvResponse\x12\x12\n\noutputPort\x18\x01 \x01(\x05\"\x14\n\x03Row\x12\r\n\x05\x66ield\x18\x01 \x03(\tB\x15\n\x08sentientB\tCSVProtosb\x06proto3')
)




_PARSECSVREQUEST = _descriptor.Descriptor(
  name='ParseCsvRequest',
  full_name='sentient.ParseCsvRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='csvPath', full_name='sentient.ParseCsvRequest.csvPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputPort', full_name='sentient.ParseCsvRequest.outputPort', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=77,
)


_PARSECSVRESPONSE = _descriptor.Descriptor(
  name='ParseCsvResponse',
  full_name='sentient.ParseCsvResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputPort', full_name='sentient.ParseCsvResponse.outputPort', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=117,
)


_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='sentient.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='sentient.Row.field', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['ParseCsvRequest'] = _PARSECSVREQUEST
DESCRIPTOR.message_types_by_name['ParseCsvResponse'] = _PARSECSVRESPONSE
DESCRIPTOR.message_types_by_name['Row'] = _ROW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseCsvRequest = _reflection.GeneratedProtocolMessageType('ParseCsvRequest', (_message.Message,), dict(
  DESCRIPTOR = _PARSECSVREQUEST,
  __module__ = 'csv_pb2'
  # @@protoc_insertion_point(class_scope:sentient.ParseCsvRequest)
  ))
_sym_db.RegisterMessage(ParseCsvRequest)

ParseCsvResponse = _reflection.GeneratedProtocolMessageType('ParseCsvResponse', (_message.Message,), dict(
  DESCRIPTOR = _PARSECSVRESPONSE,
  __module__ = 'csv_pb2'
  # @@protoc_insertion_point(class_scope:sentient.ParseCsvResponse)
  ))
_sym_db.RegisterMessage(ParseCsvResponse)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
  DESCRIPTOR = _ROW,
  __module__ = 'csv_pb2'
  # @@protoc_insertion_point(class_scope:sentient.Row)
  ))
_sym_db.RegisterMessage(Row)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
