# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parse.proto',
  package='sentient',
  syntax='proto3',
  serialized_options=_b('\n\010sentientB\013ParseProtos'),
  serialized_pb=_b('\n\x0bparse.proto\x12\x08sentient\"\x99\x01\n\x10ParseFileRequest\x12\x35\n\x08\x66ileType\x18\x01 \x01(\x0e\x32#.sentient.ParseFileRequest.FileType\x12\x10\n\x08\x66ilePath\x18\x02 \x01(\t\x12\x12\n\noutputPort\x18\x03 \x01(\r\"(\n\x08\x46ileType\x12\x07\n\x03\x43SV\x10\x00\x12\x13\n\x0f\x44ICTIONARY_LIST\x10\x01\"\'\n\x11ParseFileResponse\x12\x12\n\noutputPort\x18\x01 \x01(\r\"\x17\n\x06\x43svRow\x12\r\n\x05\x66ield\x18\x01 \x03(\t\"\x1e\n\x0e\x44ictionaryList\x12\x0c\n\x04term\x18\x01 \x03(\tB\x17\n\x08sentientB\x0bParseProtosb\x06proto3')
)



_PARSEFILEREQUEST_FILETYPE = _descriptor.EnumDescriptor(
  name='FileType',
  full_name='sentient.ParseFileRequest.FileType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CSV', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DICTIONARY_LIST', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=139,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_PARSEFILEREQUEST_FILETYPE)


_PARSEFILEREQUEST = _descriptor.Descriptor(
  name='ParseFileRequest',
  full_name='sentient.ParseFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileType', full_name='sentient.ParseFileRequest.fileType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filePath', full_name='sentient.ParseFileRequest.filePath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputPort', full_name='sentient.ParseFileRequest.outputPort', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PARSEFILEREQUEST_FILETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=179,
)


_PARSEFILERESPONSE = _descriptor.Descriptor(
  name='ParseFileResponse',
  full_name='sentient.ParseFileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputPort', full_name='sentient.ParseFileResponse.outputPort', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=220,
)


_CSVROW = _descriptor.Descriptor(
  name='CsvRow',
  full_name='sentient.CsvRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='sentient.CsvRow.field', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=245,
)


_DICTIONARYLIST = _descriptor.Descriptor(
  name='DictionaryList',
  full_name='sentient.DictionaryList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='sentient.DictionaryList.term', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=277,
)

_PARSEFILEREQUEST.fields_by_name['fileType'].enum_type = _PARSEFILEREQUEST_FILETYPE
_PARSEFILEREQUEST_FILETYPE.containing_type = _PARSEFILEREQUEST
DESCRIPTOR.message_types_by_name['ParseFileRequest'] = _PARSEFILEREQUEST
DESCRIPTOR.message_types_by_name['ParseFileResponse'] = _PARSEFILERESPONSE
DESCRIPTOR.message_types_by_name['CsvRow'] = _CSVROW
DESCRIPTOR.message_types_by_name['DictionaryList'] = _DICTIONARYLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseFileRequest = _reflection.GeneratedProtocolMessageType('ParseFileRequest', (_message.Message,), dict(
  DESCRIPTOR = _PARSEFILEREQUEST,
  __module__ = 'parse_pb2'
  # @@protoc_insertion_point(class_scope:sentient.ParseFileRequest)
  ))
_sym_db.RegisterMessage(ParseFileRequest)

ParseFileResponse = _reflection.GeneratedProtocolMessageType('ParseFileResponse', (_message.Message,), dict(
  DESCRIPTOR = _PARSEFILERESPONSE,
  __module__ = 'parse_pb2'
  # @@protoc_insertion_point(class_scope:sentient.ParseFileResponse)
  ))
_sym_db.RegisterMessage(ParseFileResponse)

CsvRow = _reflection.GeneratedProtocolMessageType('CsvRow', (_message.Message,), dict(
  DESCRIPTOR = _CSVROW,
  __module__ = 'parse_pb2'
  # @@protoc_insertion_point(class_scope:sentient.CsvRow)
  ))
_sym_db.RegisterMessage(CsvRow)

DictionaryList = _reflection.GeneratedProtocolMessageType('DictionaryList', (_message.Message,), dict(
  DESCRIPTOR = _DICTIONARYLIST,
  __module__ = 'parse_pb2'
  # @@protoc_insertion_point(class_scope:sentient.DictionaryList)
  ))
_sym_db.RegisterMessage(DictionaryList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
