# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twitter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='twitter.proto',
  package='sentient',
  syntax='proto3',
  serialized_options=_b('\n\010sentientB\rTwitterProtos'),
  serialized_pb=_b('\n\rtwitter.proto\x12\x08sentient\"@\n\x0cLabeledTweet\x12\x11\n\tsentiment\x18\x01 \x01(\r\x12\x0f\n\x07tweetId\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\tB\x19\n\x08sentientB\rTwitterProtosb\x06proto3')
)




_LABELEDTWEET = _descriptor.Descriptor(
  name='LabeledTweet',
  full_name='sentient.LabeledTweet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentiment', full_name='sentient.LabeledTweet.sentiment', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tweetId', full_name='sentient.LabeledTweet.tweetId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='sentient.LabeledTweet.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['LabeledTweet'] = _LABELEDTWEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LabeledTweet = _reflection.GeneratedProtocolMessageType('LabeledTweet', (_message.Message,), dict(
  DESCRIPTOR = _LABELEDTWEET,
  __module__ = 'twitter_pb2'
  # @@protoc_insertion_point(class_scope:sentient.LabeledTweet)
  ))
_sym_db.RegisterMessage(LabeledTweet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
