// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parse.proto

package sentient;

public final class ParseProtos {
  private ParseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParseFileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentient.ParseFileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.sentient.ParseFileRequest.FileType fileType = 1;</code>
     */
    int getFileTypeValue();
    /**
     * <code>.sentient.ParseFileRequest.FileType fileType = 1;</code>
     */
    sentient.ParseProtos.ParseFileRequest.FileType getFileType();

    /**
     * <code>string filePath = 2;</code>
     */
    java.lang.String getFilePath();
    /**
     * <code>string filePath = 2;</code>
     */
    com.google.protobuf.ByteString
        getFilePathBytes();

    /**
     * <code>uint32 outputPort = 3;</code>
     */
    int getOutputPort();
  }
  /**
   * Protobuf type {@code sentient.ParseFileRequest}
   */
  public  static final class ParseFileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentient.ParseFileRequest)
      ParseFileRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParseFileRequest.newBuilder() to construct.
    private ParseFileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseFileRequest() {
      fileType_ = 0;
      filePath_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParseFileRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              fileType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              filePath_ = s;
              break;
            }
            case 24: {

              outputPort_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentient.ParseProtos.internal_static_sentient_ParseFileRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentient.ParseProtos.internal_static_sentient_ParseFileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentient.ParseProtos.ParseFileRequest.class, sentient.ParseProtos.ParseFileRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code sentient.ParseFileRequest.FileType}
     */
    public enum FileType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CSV = 0;</code>
       */
      CSV(0),
      /**
       * <code>DICTIONARY_LIST = 1;</code>
       */
      DICTIONARY_LIST(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CSV = 0;</code>
       */
      public static final int CSV_VALUE = 0;
      /**
       * <code>DICTIONARY_LIST = 1;</code>
       */
      public static final int DICTIONARY_LIST_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static FileType valueOf(int value) {
        return forNumber(value);
      }

      public static FileType forNumber(int value) {
        switch (value) {
          case 0: return CSV;
          case 1: return DICTIONARY_LIST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FileType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          FileType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
              public FileType findValueByNumber(int number) {
                return FileType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sentient.ParseProtos.ParseFileRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final FileType[] VALUES = values();

      public static FileType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private FileType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sentient.ParseFileRequest.FileType)
    }

    public static final int FILETYPE_FIELD_NUMBER = 1;
    private int fileType_;
    /**
     * <code>.sentient.ParseFileRequest.FileType fileType = 1;</code>
     */
    public int getFileTypeValue() {
      return fileType_;
    }
    /**
     * <code>.sentient.ParseFileRequest.FileType fileType = 1;</code>
     */
    public sentient.ParseProtos.ParseFileRequest.FileType getFileType() {
      @SuppressWarnings("deprecation")
      sentient.ParseProtos.ParseFileRequest.FileType result = sentient.ParseProtos.ParseFileRequest.FileType.valueOf(fileType_);
      return result == null ? sentient.ParseProtos.ParseFileRequest.FileType.UNRECOGNIZED : result;
    }

    public static final int FILEPATH_FIELD_NUMBER = 2;
    private volatile java.lang.Object filePath_;
    /**
     * <code>string filePath = 2;</code>
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }
    /**
     * <code>string filePath = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OUTPUTPORT_FIELD_NUMBER = 3;
    private int outputPort_;
    /**
     * <code>uint32 outputPort = 3;</code>
     */
    public int getOutputPort() {
      return outputPort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fileType_ != sentient.ParseProtos.ParseFileRequest.FileType.CSV.getNumber()) {
        output.writeEnum(1, fileType_);
      }
      if (!getFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filePath_);
      }
      if (outputPort_ != 0) {
        output.writeUInt32(3, outputPort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fileType_ != sentient.ParseProtos.ParseFileRequest.FileType.CSV.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, fileType_);
      }
      if (!getFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filePath_);
      }
      if (outputPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, outputPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentient.ParseProtos.ParseFileRequest)) {
        return super.equals(obj);
      }
      sentient.ParseProtos.ParseFileRequest other = (sentient.ParseProtos.ParseFileRequest) obj;

      if (fileType_ != other.fileType_) return false;
      if (!getFilePath()
          .equals(other.getFilePath())) return false;
      if (getOutputPort()
          != other.getOutputPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + fileType_;
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (37 * hash) + OUTPUTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getOutputPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentient.ParseProtos.ParseFileRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.ParseFileRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.ParseFileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.ParseFileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.ParseFileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.ParseFileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.ParseFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentient.ParseProtos.ParseFileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentient.ParseFileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentient.ParseFileRequest)
        sentient.ParseProtos.ParseFileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentient.ParseProtos.internal_static_sentient_ParseFileRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentient.ParseProtos.internal_static_sentient_ParseFileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentient.ParseProtos.ParseFileRequest.class, sentient.ParseProtos.ParseFileRequest.Builder.class);
      }

      // Construct using sentient.ParseProtos.ParseFileRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fileType_ = 0;

        filePath_ = "";

        outputPort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentient.ParseProtos.internal_static_sentient_ParseFileRequest_descriptor;
      }

      @java.lang.Override
      public sentient.ParseProtos.ParseFileRequest getDefaultInstanceForType() {
        return sentient.ParseProtos.ParseFileRequest.getDefaultInstance();
      }

      @java.lang.Override
      public sentient.ParseProtos.ParseFileRequest build() {
        sentient.ParseProtos.ParseFileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentient.ParseProtos.ParseFileRequest buildPartial() {
        sentient.ParseProtos.ParseFileRequest result = new sentient.ParseProtos.ParseFileRequest(this);
        result.fileType_ = fileType_;
        result.filePath_ = filePath_;
        result.outputPort_ = outputPort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentient.ParseProtos.ParseFileRequest) {
          return mergeFrom((sentient.ParseProtos.ParseFileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentient.ParseProtos.ParseFileRequest other) {
        if (other == sentient.ParseProtos.ParseFileRequest.getDefaultInstance()) return this;
        if (other.fileType_ != 0) {
          setFileTypeValue(other.getFileTypeValue());
        }
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          onChanged();
        }
        if (other.getOutputPort() != 0) {
          setOutputPort(other.getOutputPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sentient.ParseProtos.ParseFileRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sentient.ParseProtos.ParseFileRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int fileType_ = 0;
      /**
       * <code>.sentient.ParseFileRequest.FileType fileType = 1;</code>
       */
      public int getFileTypeValue() {
        return fileType_;
      }
      /**
       * <code>.sentient.ParseFileRequest.FileType fileType = 1;</code>
       */
      public Builder setFileTypeValue(int value) {
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.sentient.ParseFileRequest.FileType fileType = 1;</code>
       */
      public sentient.ParseProtos.ParseFileRequest.FileType getFileType() {
        @SuppressWarnings("deprecation")
        sentient.ParseProtos.ParseFileRequest.FileType result = sentient.ParseProtos.ParseFileRequest.FileType.valueOf(fileType_);
        return result == null ? sentient.ParseProtos.ParseFileRequest.FileType.UNRECOGNIZED : result;
      }
      /**
       * <code>.sentient.ParseFileRequest.FileType fileType = 1;</code>
       */
      public Builder setFileType(sentient.ParseProtos.ParseFileRequest.FileType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fileType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.sentient.ParseFileRequest.FileType fileType = 1;</code>
       */
      public Builder clearFileType() {
        
        fileType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object filePath_ = "";
      /**
       * <code>string filePath = 2;</code>
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filePath = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filePath = 2;</code>
       */
      public Builder setFilePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filePath = 2;</code>
       */
      public Builder clearFilePath() {
        
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      /**
       * <code>string filePath = 2;</code>
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filePath_ = value;
        onChanged();
        return this;
      }

      private int outputPort_ ;
      /**
       * <code>uint32 outputPort = 3;</code>
       */
      public int getOutputPort() {
        return outputPort_;
      }
      /**
       * <code>uint32 outputPort = 3;</code>
       */
      public Builder setOutputPort(int value) {
        
        outputPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 outputPort = 3;</code>
       */
      public Builder clearOutputPort() {
        
        outputPort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentient.ParseFileRequest)
    }

    // @@protoc_insertion_point(class_scope:sentient.ParseFileRequest)
    private static final sentient.ParseProtos.ParseFileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentient.ParseProtos.ParseFileRequest();
    }

    public static sentient.ParseProtos.ParseFileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseFileRequest>
        PARSER = new com.google.protobuf.AbstractParser<ParseFileRequest>() {
      @java.lang.Override
      public ParseFileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParseFileRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParseFileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseFileRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentient.ParseProtos.ParseFileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParseFileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentient.ParseFileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 outputPort = 1;</code>
     */
    int getOutputPort();
  }
  /**
   * Protobuf type {@code sentient.ParseFileResponse}
   */
  public  static final class ParseFileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentient.ParseFileResponse)
      ParseFileResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParseFileResponse.newBuilder() to construct.
    private ParseFileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseFileResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParseFileResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              outputPort_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentient.ParseProtos.internal_static_sentient_ParseFileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentient.ParseProtos.internal_static_sentient_ParseFileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentient.ParseProtos.ParseFileResponse.class, sentient.ParseProtos.ParseFileResponse.Builder.class);
    }

    public static final int OUTPUTPORT_FIELD_NUMBER = 1;
    private int outputPort_;
    /**
     * <code>uint32 outputPort = 1;</code>
     */
    public int getOutputPort() {
      return outputPort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (outputPort_ != 0) {
        output.writeUInt32(1, outputPort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (outputPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, outputPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentient.ParseProtos.ParseFileResponse)) {
        return super.equals(obj);
      }
      sentient.ParseProtos.ParseFileResponse other = (sentient.ParseProtos.ParseFileResponse) obj;

      if (getOutputPort()
          != other.getOutputPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OUTPUTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getOutputPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentient.ParseProtos.ParseFileResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.ParseFileResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.ParseFileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.ParseFileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.ParseFileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.ParseFileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentient.ParseProtos.ParseFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.ParseFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentient.ParseProtos.ParseFileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentient.ParseFileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentient.ParseFileResponse)
        sentient.ParseProtos.ParseFileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentient.ParseProtos.internal_static_sentient_ParseFileResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentient.ParseProtos.internal_static_sentient_ParseFileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentient.ParseProtos.ParseFileResponse.class, sentient.ParseProtos.ParseFileResponse.Builder.class);
      }

      // Construct using sentient.ParseProtos.ParseFileResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        outputPort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentient.ParseProtos.internal_static_sentient_ParseFileResponse_descriptor;
      }

      @java.lang.Override
      public sentient.ParseProtos.ParseFileResponse getDefaultInstanceForType() {
        return sentient.ParseProtos.ParseFileResponse.getDefaultInstance();
      }

      @java.lang.Override
      public sentient.ParseProtos.ParseFileResponse build() {
        sentient.ParseProtos.ParseFileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentient.ParseProtos.ParseFileResponse buildPartial() {
        sentient.ParseProtos.ParseFileResponse result = new sentient.ParseProtos.ParseFileResponse(this);
        result.outputPort_ = outputPort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentient.ParseProtos.ParseFileResponse) {
          return mergeFrom((sentient.ParseProtos.ParseFileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentient.ParseProtos.ParseFileResponse other) {
        if (other == sentient.ParseProtos.ParseFileResponse.getDefaultInstance()) return this;
        if (other.getOutputPort() != 0) {
          setOutputPort(other.getOutputPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sentient.ParseProtos.ParseFileResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sentient.ParseProtos.ParseFileResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int outputPort_ ;
      /**
       * <code>uint32 outputPort = 1;</code>
       */
      public int getOutputPort() {
        return outputPort_;
      }
      /**
       * <code>uint32 outputPort = 1;</code>
       */
      public Builder setOutputPort(int value) {
        
        outputPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 outputPort = 1;</code>
       */
      public Builder clearOutputPort() {
        
        outputPort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentient.ParseFileResponse)
    }

    // @@protoc_insertion_point(class_scope:sentient.ParseFileResponse)
    private static final sentient.ParseProtos.ParseFileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentient.ParseProtos.ParseFileResponse();
    }

    public static sentient.ParseProtos.ParseFileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseFileResponse>
        PARSER = new com.google.protobuf.AbstractParser<ParseFileResponse>() {
      @java.lang.Override
      public ParseFileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParseFileResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParseFileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseFileResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentient.ParseProtos.ParseFileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CsvRowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentient.CsvRow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string field = 1;</code>
     */
    java.util.List<java.lang.String>
        getFieldList();
    /**
     * <code>repeated string field = 1;</code>
     */
    int getFieldCount();
    /**
     * <code>repeated string field = 1;</code>
     */
    java.lang.String getField(int index);
    /**
     * <code>repeated string field = 1;</code>
     */
    com.google.protobuf.ByteString
        getFieldBytes(int index);
  }
  /**
   * Protobuf type {@code sentient.CsvRow}
   */
  public  static final class CsvRow extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentient.CsvRow)
      CsvRowOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CsvRow.newBuilder() to construct.
    private CsvRow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CsvRow() {
      field_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CsvRow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                field_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              field_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          field_ = field_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentient.ParseProtos.internal_static_sentient_CsvRow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentient.ParseProtos.internal_static_sentient_CsvRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentient.ParseProtos.CsvRow.class, sentient.ParseProtos.CsvRow.Builder.class);
    }

    public static final int FIELD_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList field_;
    /**
     * <code>repeated string field = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFieldList() {
      return field_;
    }
    /**
     * <code>repeated string field = 1;</code>
     */
    public int getFieldCount() {
      return field_.size();
    }
    /**
     * <code>repeated string field = 1;</code>
     */
    public java.lang.String getField(int index) {
      return field_.get(index);
    }
    /**
     * <code>repeated string field = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFieldBytes(int index) {
      return field_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < field_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, field_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < field_.size(); i++) {
          dataSize += computeStringSizeNoTag(field_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFieldList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentient.ParseProtos.CsvRow)) {
        return super.equals(obj);
      }
      sentient.ParseProtos.CsvRow other = (sentient.ParseProtos.CsvRow) obj;

      if (!getFieldList()
          .equals(other.getFieldList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFieldCount() > 0) {
        hash = (37 * hash) + FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getFieldList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentient.ParseProtos.CsvRow parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.CsvRow parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.CsvRow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.CsvRow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.CsvRow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.CsvRow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.CsvRow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.CsvRow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentient.ParseProtos.CsvRow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.CsvRow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentient.ParseProtos.CsvRow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.CsvRow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentient.ParseProtos.CsvRow prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentient.CsvRow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentient.CsvRow)
        sentient.ParseProtos.CsvRowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentient.ParseProtos.internal_static_sentient_CsvRow_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentient.ParseProtos.internal_static_sentient_CsvRow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentient.ParseProtos.CsvRow.class, sentient.ParseProtos.CsvRow.Builder.class);
      }

      // Construct using sentient.ParseProtos.CsvRow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        field_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentient.ParseProtos.internal_static_sentient_CsvRow_descriptor;
      }

      @java.lang.Override
      public sentient.ParseProtos.CsvRow getDefaultInstanceForType() {
        return sentient.ParseProtos.CsvRow.getDefaultInstance();
      }

      @java.lang.Override
      public sentient.ParseProtos.CsvRow build() {
        sentient.ParseProtos.CsvRow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentient.ParseProtos.CsvRow buildPartial() {
        sentient.ParseProtos.CsvRow result = new sentient.ParseProtos.CsvRow(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          field_ = field_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.field_ = field_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentient.ParseProtos.CsvRow) {
          return mergeFrom((sentient.ParseProtos.CsvRow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentient.ParseProtos.CsvRow other) {
        if (other == sentient.ParseProtos.CsvRow.getDefaultInstance()) return this;
        if (!other.field_.isEmpty()) {
          if (field_.isEmpty()) {
            field_ = other.field_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFieldIsMutable();
            field_.addAll(other.field_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sentient.ParseProtos.CsvRow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sentient.ParseProtos.CsvRow) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList field_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          field_ = new com.google.protobuf.LazyStringArrayList(field_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string field = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFieldList() {
        return field_.getUnmodifiableView();
      }
      /**
       * <code>repeated string field = 1;</code>
       */
      public int getFieldCount() {
        return field_.size();
      }
      /**
       * <code>repeated string field = 1;</code>
       */
      public java.lang.String getField(int index) {
        return field_.get(index);
      }
      /**
       * <code>repeated string field = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFieldBytes(int index) {
        return field_.getByteString(index);
      }
      /**
       * <code>repeated string field = 1;</code>
       */
      public Builder setField(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldIsMutable();
        field_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field = 1;</code>
       */
      public Builder addField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldIsMutable();
        field_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field = 1;</code>
       */
      public Builder addAllField(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, field_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field = 1;</code>
       */
      public Builder clearField() {
        field_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field = 1;</code>
       */
      public Builder addFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFieldIsMutable();
        field_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentient.CsvRow)
    }

    // @@protoc_insertion_point(class_scope:sentient.CsvRow)
    private static final sentient.ParseProtos.CsvRow DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentient.ParseProtos.CsvRow();
    }

    public static sentient.ParseProtos.CsvRow getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CsvRow>
        PARSER = new com.google.protobuf.AbstractParser<CsvRow>() {
      @java.lang.Override
      public CsvRow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CsvRow(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CsvRow> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CsvRow> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentient.ParseProtos.CsvRow getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DictionaryListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentient.DictionaryList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string term = 1;</code>
     */
    java.util.List<java.lang.String>
        getTermList();
    /**
     * <code>repeated string term = 1;</code>
     */
    int getTermCount();
    /**
     * <code>repeated string term = 1;</code>
     */
    java.lang.String getTerm(int index);
    /**
     * <code>repeated string term = 1;</code>
     */
    com.google.protobuf.ByteString
        getTermBytes(int index);
  }
  /**
   * Protobuf type {@code sentient.DictionaryList}
   */
  public  static final class DictionaryList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentient.DictionaryList)
      DictionaryListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DictionaryList.newBuilder() to construct.
    private DictionaryList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DictionaryList() {
      term_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DictionaryList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                term_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              term_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          term_ = term_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentient.ParseProtos.internal_static_sentient_DictionaryList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentient.ParseProtos.internal_static_sentient_DictionaryList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentient.ParseProtos.DictionaryList.class, sentient.ParseProtos.DictionaryList.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList term_;
    /**
     * <code>repeated string term = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTermList() {
      return term_;
    }
    /**
     * <code>repeated string term = 1;</code>
     */
    public int getTermCount() {
      return term_.size();
    }
    /**
     * <code>repeated string term = 1;</code>
     */
    public java.lang.String getTerm(int index) {
      return term_.get(index);
    }
    /**
     * <code>repeated string term = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTermBytes(int index) {
      return term_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < term_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, term_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < term_.size(); i++) {
          dataSize += computeStringSizeNoTag(term_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTermList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentient.ParseProtos.DictionaryList)) {
        return super.equals(obj);
      }
      sentient.ParseProtos.DictionaryList other = (sentient.ParseProtos.DictionaryList) obj;

      if (!getTermList()
          .equals(other.getTermList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTermCount() > 0) {
        hash = (37 * hash) + TERM_FIELD_NUMBER;
        hash = (53 * hash) + getTermList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentient.ParseProtos.DictionaryList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.DictionaryList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.DictionaryList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.DictionaryList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.DictionaryList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentient.ParseProtos.DictionaryList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentient.ParseProtos.DictionaryList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.DictionaryList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentient.ParseProtos.DictionaryList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.DictionaryList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentient.ParseProtos.DictionaryList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentient.ParseProtos.DictionaryList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentient.ParseProtos.DictionaryList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentient.DictionaryList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentient.DictionaryList)
        sentient.ParseProtos.DictionaryListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentient.ParseProtos.internal_static_sentient_DictionaryList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentient.ParseProtos.internal_static_sentient_DictionaryList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentient.ParseProtos.DictionaryList.class, sentient.ParseProtos.DictionaryList.Builder.class);
      }

      // Construct using sentient.ParseProtos.DictionaryList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        term_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentient.ParseProtos.internal_static_sentient_DictionaryList_descriptor;
      }

      @java.lang.Override
      public sentient.ParseProtos.DictionaryList getDefaultInstanceForType() {
        return sentient.ParseProtos.DictionaryList.getDefaultInstance();
      }

      @java.lang.Override
      public sentient.ParseProtos.DictionaryList build() {
        sentient.ParseProtos.DictionaryList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentient.ParseProtos.DictionaryList buildPartial() {
        sentient.ParseProtos.DictionaryList result = new sentient.ParseProtos.DictionaryList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          term_ = term_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.term_ = term_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentient.ParseProtos.DictionaryList) {
          return mergeFrom((sentient.ParseProtos.DictionaryList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentient.ParseProtos.DictionaryList other) {
        if (other == sentient.ParseProtos.DictionaryList.getDefaultInstance()) return this;
        if (!other.term_.isEmpty()) {
          if (term_.isEmpty()) {
            term_ = other.term_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTermIsMutable();
            term_.addAll(other.term_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sentient.ParseProtos.DictionaryList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sentient.ParseProtos.DictionaryList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList term_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTermIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          term_ = new com.google.protobuf.LazyStringArrayList(term_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string term = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTermList() {
        return term_.getUnmodifiableView();
      }
      /**
       * <code>repeated string term = 1;</code>
       */
      public int getTermCount() {
        return term_.size();
      }
      /**
       * <code>repeated string term = 1;</code>
       */
      public java.lang.String getTerm(int index) {
        return term_.get(index);
      }
      /**
       * <code>repeated string term = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTermBytes(int index) {
        return term_.getByteString(index);
      }
      /**
       * <code>repeated string term = 1;</code>
       */
      public Builder setTerm(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTermIsMutable();
        term_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string term = 1;</code>
       */
      public Builder addTerm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTermIsMutable();
        term_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string term = 1;</code>
       */
      public Builder addAllTerm(
          java.lang.Iterable<java.lang.String> values) {
        ensureTermIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, term_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string term = 1;</code>
       */
      public Builder clearTerm() {
        term_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string term = 1;</code>
       */
      public Builder addTermBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTermIsMutable();
        term_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentient.DictionaryList)
    }

    // @@protoc_insertion_point(class_scope:sentient.DictionaryList)
    private static final sentient.ParseProtos.DictionaryList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentient.ParseProtos.DictionaryList();
    }

    public static sentient.ParseProtos.DictionaryList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DictionaryList>
        PARSER = new com.google.protobuf.AbstractParser<DictionaryList>() {
      @java.lang.Override
      public DictionaryList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DictionaryList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DictionaryList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DictionaryList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentient.ParseProtos.DictionaryList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentient_ParseFileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentient_ParseFileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentient_ParseFileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentient_ParseFileResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentient_CsvRow_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentient_CsvRow_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentient_DictionaryList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentient_DictionaryList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013parse.proto\022\010sentient\"\231\001\n\020ParseFileReq" +
      "uest\0225\n\010fileType\030\001 \001(\0162#.sentient.ParseF" +
      "ileRequest.FileType\022\020\n\010filePath\030\002 \001(\t\022\022\n" +
      "\noutputPort\030\003 \001(\r\"(\n\010FileType\022\007\n\003CSV\020\000\022\023" +
      "\n\017DICTIONARY_LIST\020\001\"\'\n\021ParseFileResponse" +
      "\022\022\n\noutputPort\030\001 \001(\r\"\027\n\006CsvRow\022\r\n\005field\030" +
      "\001 \003(\t\"\036\n\016DictionaryList\022\014\n\004term\030\001 \003(\tB\027\n" +
      "\010sentientB\013ParseProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sentient_ParseFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sentient_ParseFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentient_ParseFileRequest_descriptor,
        new java.lang.String[] { "FileType", "FilePath", "OutputPort", });
    internal_static_sentient_ParseFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sentient_ParseFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentient_ParseFileResponse_descriptor,
        new java.lang.String[] { "OutputPort", });
    internal_static_sentient_CsvRow_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sentient_CsvRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentient_CsvRow_descriptor,
        new java.lang.String[] { "Field", });
    internal_static_sentient_DictionaryList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_sentient_DictionaryList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentient_DictionaryList_descriptor,
        new java.lang.String[] { "Term", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
